"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruang',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_ruang', sa.String(length=255), nullable=False),
    sa.Column('jenis', sa.Enum('lab', 'bengkel', name='jenisruang'), nullable=False),
    sa.Column('menggunakan_kunci', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'siswa', name='userrole'), nullable=False),
    sa.Column('kelas', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fasilitas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ruang_id', sa.Integer(), nullable=False),
    sa.Column('nama_fasilitas', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ruang_id'], ['ruang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laporan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ruang_id', sa.Integer(), nullable=False),
    sa.Column('foto_kegiatan', sa.String(length=255), nullable=False),
    sa.Column('foto_kunci', sa.String(length=255), nullable=True),
    sa.Column('jam_pelajaran', sa.Integer(), nullable=False),
    sa.Column('fasilitas_digunakan', sa.JSON(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'disetujui', 'ditolak', name='statuslaporan'), nullable=True),
    sa.Column('alasan_penolakan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ruang_id'], ['ruang.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laporan')
    op.drop_table('fasilitas')
    op.drop_table('users')
    op.drop_table('ruang')
    # ### end Alembic commands ###